language: swift
os: osx
osx_image: xcode12.2
xcode_workspace: SocialLite.xcworkspace
xcode_scheme: SocialLite
xcode_destination: platform=iOS Simulator,OS=14.2,name=iPhone 12
branches:
  only:
  - main
  - develop
jobs:
  include:
    - stage: Unit Test
      before_script:
      - bash <(curl -Ls https://coverage.codacy.com/get.sh) download
      after_success:
      - gem install slather
      - slather
      - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r output/cobertura.xml
cache:
  timeout: 1000
  cocoapods: true
  directories:
    # This contains the CFamily cache. According to https://docs.travis-ci.com/user/caching/#pull-request-builds-and-caches,
    # for a PR, it will use the cache of the target branch if the branch of the PR does not already have its cache.
    - $HOME/.cfamily
